# Generated by Django 2.2.3 on 2019-07-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
