# Generated by Django 2.2.3 on 2019-07-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0002_auto_20190716_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
