# Generated by Django 2.2.3 on 2019-07-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
